### ISSUE TITLE
Publish the binaries as packages?

### ISSUE THREAD

**Issue by aniketbiprojit** [matter-labs/zksolc-bin#10]
Is there a place where these have been published as packages? GitHub download speeds are abysmal.

**Comment by hedgar2017** [comment]
@aniketbiprojit indeed, GitHub has been awful lately and introduced some downtime.
We're currently switching to GitHub releases.

**Comment by hedgar2017** [comment]
All binaries will now be available at the releases, where the infrastructure is significantly better.
