### ISSUE TITLE
Why I am not eligible for zkSync Era nft sumonxyx nft 

### ISSUE THREAD

**Issue by Armankhan566** [matter-labs/zksolc-bin#13]
I do all work in zk sync development my volume in zkSync Era is 1150 dollar above

My address is 0x88686F7A5Db76c4462efcc0b7CAE5c4F9A3c15F0
Please why I am not eligible for zkSy
![Screenshot_2023-09-20-09-16-58-89_d4b821f22c36211daa9077338f9854d0](https://github.com/matter-labs/zksolc-bin/assets/124797941/f48e2952-c0e5-4432-ba1b-7d683a49f5a1)
nc Era nft matter labs

**Comment by hedgar2017** [comment]
@Armankhan566 please avoid spamming in Matter Labs repositories.
Further attemps will result into a permanent ban in our organization.
Thanks for understanding!
