### ISSUE TITLE
deploy zbin compiled by zksolc-bin without hardhat plugin

### ISSUE THREAD

**Issue by simonatweb3** [matter-labs/zksolc-bin#19]
Hi Team，

I'm trying to deploy my smart contract on zksync era, after compile solidity smart contract with zksolc,

```shell
    zksolc-macosx-amd64-v1.4.0 -o ./build --overwrite smartcontract.sol --bin
```

the output is a .zbin file.

My question is , how can I deploy the .zbin file, just as deploy bytecode with create2 as the normal EVM deploy ?
```typescript
        await wallet.sendTransaction(
            {
                to : ethers.constants.AddressZero,
                data : compiledContract.bytecode,
                gasLimit : 5000000
            }
       )
```

Since I am not familiar with hardhat，and it's a heavy burden for me to learn it from start, so the below link is not a good guide for me.
https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-deploy.html.

**Comment by simonatweb3** [comment]
@hedgar2017 Ser, could you please help check?

**Comment by hedgar2017** [comment]
@MexicanAce @githubdoramon not a compiler issue. Could you transfer it to the proper place?

**Comment by uF4No** [comment]
I suggest you to read the [differences with Ethereum when it comes to smart contract deployments](https://docs.zksync.io/build/developer-reference/ethereum-differences/contract-deployment). If you have other questions, please [create a new thread in our GitHub Discussions](https://github.com/zkSync-Community-Hub/zksync-developers/discussions) and we'll try to help
