### ISSUE TITLE
when this link will be updated in the package? 

### ISSUE THREAD

**Issue by Bvvvp009** [matter-labs/zksolc-bin#2]
when  i try to compile contracts it showing this error.
Downloading zksolc 1.2.0
Error in plugin @matterlabs/hardhat-zksync-solc: Failed to download https://github.com/matter-labs/zksolc-bin/raw/main/win32-amd64/zksolc-win32-amd64-v1.2.0 - 404 received.
 that link pointing to the last commit.

**Comment by typicalHuman** [comment]
same issue...

**Comment by DDDimatestx** [comment]
Same..

**Comment by uF4No** [comment]
we've updated the protocol so devs should use `zksolc` version 1.3.x. Version `1.3.8` is the latest available currently. In addition, please update ` @matterlabs/hardhat-zksync-solc ` to the latest version (currently 0.3.16)

**Comment by hedgar2017** [comment]
Windows support was added after 1.2.0, so older versions were never released.
